"""MARKER ASSEMBLY CALIBRATION -- where a held object sits on a fixed one, measured by sight.

    python -m urlab.apps.marker_assembly_calibration --set marker_assembly=tile_on_plate

Writes one entry into configs/marker_assemblies.yaml: for every marker on the FIXED object, the
HELD object's mating frame at its assembled position, in that marker's own frame.
apps/coupler_marker_assemble drives to it.

VISUAL, NOTHING HELD. Assemble the two objects BY HAND, then let the camera look at both. One
sweep sees the fixed object's markers and the held object's markers together, so

    T_base_goal  = T_base_held_marker @ T_held_marker_grasp     (objects.yaml, voted + joint PnP)
    T_fixed_goal = inverse(T_base_fixed_marker) @ T_base_goal   (per fixed marker)

The robot only carries the camera, and base_link cancels: both markers are measured from the
same views, so what is stored is purely a relationship between the two objects.

WHAT THAT INHERITS. The held object's grasp offsets come from its objects.yaml calibration, so
an error there is baked into every entry measured through it -- re-run urlab.apps.
object_calibration before this if that object's markers were moved. The fixed object's markers
need no prior calibration: this run IS their calibration.

CAPTURES. Each capture returns to the same view and sweeps again. Between captures you are asked
to RE-SEAT the held object; the spread across captures is then how repeatably the assembly
seats, plus marker noise. Leaving it in place measures marker noise alone.

START POSE. `start_joints_deg`, when set, is moved to ONCE before anything else -- a known
place to begin from, near the scene; the hand-guiding (or the move to view_joints_deg) starts
there.

THE VIEW POSE IS RECORDED. Unless `record_view_joints: false`, the joints the markers were seen
from are written with the entry, and the run-time app looks at the fixed object from there:
seeing it from the same place cancels the part of the error that depends on viewpoint.

Output: data/experiments/marker_assembly_calibration_<stamp>/ -- the yaml entry, a per-capture
CSV and marker_images/. The catalogue is MERGED (other assemblies left alone) and the previous
version is backed up into the run directory first.
"""

import csv as _csv
import os
import shutil
from datetime import datetime

import numpy as np

from .. import behaviors as bt
from .. import log as urlog
from .. import tool_frames
from ..apps._common import ask, experiment_dir, prompts_off
from ..skills import marker_localize as mloc
from ..transforms import inverse, matrix_to_xyzrpy, pose_error
from ._runner import run_app
from .coupler_assembly_calibration import fuse_approaches
from .coupler_marker_assemble import marker_to_marker
from .coupler_pick_place import object_rig
from .marker_calibration import parse_markers

log = urlog.get('marker-asm-calib')

_CSV_HEADER = ['capture', 'fixed_marker', 'views', 'goal_x_mm', 'goal_y_mm', 'goal_z_mm',
               'goal_roll_deg', 'goal_pitch_deg', 'goal_yaw_deg', 'point_dev_mm', 'rot_dev_deg']


# ---------------------------------------------------------------------------- the catalogue
_HEADER = """\
# ============================================================================
# MARKER ASSEMBLIES -- where a HELD object goes, relative to the markers on a FIXED one.
#
# GENERATED by urlab.apps.marker_assembly_calibration, which rewrites this whole file on every
# run, merging in the one assembly it measured -- COMMENTS ADDED BY HAND DO NOT SURVIVE.
#
# Each fixed marker stores the held object's MATING FRAME at its assembled position, in that
# marker's own frame (marker <- held mating frame). Once picked, the held mating frame IS
# configs/frames.yaml's `coupler_mate`, so at run time urlab.apps.coupler_marker_assemble drives
#
#     T_base_coupler_goal = T_base_fixed_marker @ T_marker_goal
#
# and every fixed marker in view votes on it. `held_object` names the configs/objects.yaml
# entry that is picked; its grasp offsets were composed in when this was measured.
#
# view_joints_deg is where the fixed markers were seen from; the run looks from there too.
# residual_mm / residual_deg are the spread across captures (re-seats + marker noise).
# ============================================================================
"""


def entry_block(name, entry):
    """One assembly as yaml text -- what load_marker_assemblies reads back."""
    out = [f'  {name}:', f"    held_object: {entry['held_object']}"]
    if entry.get('dictionary'):
        out.append(f"    dictionary: {entry['dictionary']}")
    if entry.get('view_joints') is not None:
        out.append('    view_joints_deg: [%s]' % ', '.join(
            '%+.3f' % v for v in np.degrees(np.asarray(entry['view_joints'], dtype=float))))
    out.append('    markers:')
    for mid in sorted(entry['markers']):
        m = entry['markers'][mid]
        xyz, rpy = matrix_to_xyzrpy(m['T_marker_goal'])
        out += [f'      {mid}:',
                f"        size_mm: {m['size_m'] * 1000.0:.2f}",
                '        xyz_mm:  [%s]' % ', '.join('%+.2f' % (v * 1000.0) for v in xyz),
                '        rpy_deg: [%s]' % ', '.join('%+.2f' % np.degrees(v) for v in rpy)]
        out += _meta_lines('        ', m.get('meta') or {})
    out += _meta_lines('    ', entry.get('meta') or {})
    return '\n'.join(out)


def _meta_lines(indent, meta):
    return ['%s%s: %s' % (indent, k, f'{meta[k]:.2f}' if isinstance(meta[k], float) else meta[k])
            for k in ('captures', 'views', 'residual_mm', 'residual_deg', 'measured', 'note')
            if k in meta]


def yaml_document(assemblies, stamp=None):
    """The whole catalogue as text: the header plus one block per assembly."""
    lines = [_HEADER.rstrip('\n'), '']
    if stamp:
        lines += [f'# Last written {stamp}.', '']
    if not assemblies:
        return '\n'.join(lines + ['marker_assemblies: {}']) + '\n'
    lines.append('marker_assemblies:')
    lines += [entry_block(name, assemblies[name]) for name in sorted(assemblies)]
    return '\n'.join(lines) + '\n'


def joints_deg(cfg, key):
    """An optional `<key>: [6 joint angles, deg]` -> radians, or None when unset."""
    q = cfg.get(key)
    if q is None:
        return None
    q = np.radians(np.asarray(q, dtype=float))
    if q.shape != (6,):
        raise ValueError(f'{key} must be 6 joint angles in deg, got {cfg.get(key)!r}')
    return q


def goal_in_fixed_markers(T_base_goal, fixed_fused):
    """{fixed marker id: T_marker_goal} -- the held mating frame in each fixed marker's frame.
    Pure, so the composition is testable without a camera."""
    return {mid: inverse(f[0]) @ T_base_goal for mid, f in fixed_fused.items()}


# ---------------------------------------------------------------------------- the run
class _MarkerAssemblyCalibration:
    """One assembly: look at both objects, solve the held mating frame in the fixed markers,
    repeat, fuse, write the catalogue."""

    def __init__(self, cfg, robot, camera, detector, plan, name, held_name, held_obj,
                 fixed_sizes, out_dir, q_start=None):
        self.cfg = cfg
        self.robot = robot
        self.camera = camera
        self.detector = detector
        self.plan = plan
        self.name = name
        self.held_name = held_name
        self.held_rig = object_rig(held_obj, cfg.get_path('aruco.dictionary'))
        self.fixed_sizes = dict(fixed_sizes)
        self.sizes = dict(self.fixed_sizes)
        self.sizes.update(tool_frames.marker_sizes(self.held_rig))
        self.out_dir = out_dir
        self.images = mloc.MarkerImageWriter(out_dir, detector,
                                             enabled=getattr(plan, 'save_images', True))
        self.captures = max(1, int(cfg.get('captures', 3)))
        self.q_start = q_start
        self.q_view = None
        self.goals = []            # per capture: T_base_goal (the held mating frame)
        self.scans = []            # per capture: {fixed id: fused (T, lin, ang, n, w)}
        self.offsets = {}          # {fixed id: [T_marker_goal per capture it was seen in]}
        self.results = {}          # {fixed id: (T_marker_goal, res_mm, res_deg)}

    # ---- collect -----------------------------------------------------------------------------
    def to_start(self):
        """`start_joints_deg`, once, before the first capture. Unset = begin where the arm is."""
        if self.q_start is None:
            return True
        return self.robot.move_joints(self.q_start, label='start pose')

    def collect(self):
        try:
            return self._collect()
        finally:
            self.images.finish(
                [f'marker assembly {self.name}: {self.held_name} onto fixed markers '
                 f'{sorted(self.fixed_sizes)}',
                 f'{len(self.goals)} of {self.captures} capture(s) solved']
                + ['capture %d: fixed marker(s) %s' % (k + 1, sorted(scan))
                   for k, scan in enumerate(self.scans)])

    def _collect(self):
        for k in range(self.captures):
            log.info('---- CAPTURE %d of %d ----', k + 1, self.captures)
            if k > 0 and not self._reseat(k):
                return False
            if not self._to_view():
                return False
            if not self._capture(k):
                return False
        return bool(self.offsets)

    def _reseat(self, k):
        if self.robot.arm.dry_run or prompts_off(self.cfg):
            return True
        return ask(f'RE-SEAT {self.held_name!r} in its assembled position for capture {k + 1} '
                   '(or leave it, to measure marker noise only), then press Enter (q to stop): ')

    def _to_view(self):
        """`view_joints_deg` when configured; otherwise hand-guided ONCE and returned to after,
        so every capture sees the pair from the same place."""
        if self.q_view is None and self.cfg.get('view_joints_deg') is not None:
            self.q_view = np.radians(np.asarray(self.cfg['view_joints_deg'], dtype=float))
        if self.q_view is not None:
            return self.robot.move_joints(self.q_view, label='assembly view pose')
        if not self._hand_guide('Push the arm until the markers on BOTH objects are in view, '
                                'then press Enter (q to abort): '):
            return False
        self.q_view = np.asarray(self.robot.arm.q(), dtype=float)
        return True

    def _capture(self, k):
        """One sweep over both objects' markers, then the held goal and its fixed-marker offsets.

        ONE SET OF VIEWS FOR BOTH. Base_link only cancels if the two objects are measured from
        the same camera poses -- so they are swept together, not one after the other."""
        T_overview = self.robot.camera()
        corner_views = []
        seen = mloc.sweep(self.robot, self.camera, self.detector, self.plan,
                          wanted=set(self.sizes),
                          on_view=lambda i, f, p: self.images.sweep_view(k * 100 + i, f, p),
                          corner_log=corner_views)
        if self.plan.servo.enabled and seen:
            mloc.merge_refined(seen, mloc.servo_refine(
                self.robot, self.camera, self.detector, self.plan, seen, T_overview=T_overview,
                on_view=lambda mid, j, f, p: self.images.servo_view(mid, k * 100 + j, f, p),
                on_iteration=lambda mid, it, f, p: self.images.servo_iteration_view(
                    mid, k * 100 + it, f, p),
                corner_log=corner_views))
        fused = mloc.fuse_markers(seen, self.plan) if seen else {}
        if fused and getattr(self.plan, 'multiview_refine', True):
            for mid, (T_ref, _rms, _n) in mloc.refine_markers_multiview(
                    fused, corner_views, self.sizes, self.plan).items():
                fused[mid] = (T_ref,) + tuple(fused[mid][1:])

        held = {m: f for m, f in fused.items() if m in self.held_rig['markers']}
        fixed = {m: f for m, f in fused.items() if m in self.fixed_sizes}
        for what, got, declared in (('held object', held, self.held_rig['markers']),
                                    ('fixed object', fixed, self.fixed_sizes)):
            missing = sorted(set(declared) - set(got))
            if missing:
                log.warning('  %s marker(s) %s not fused on capture %d.', what,
                            ', '.join(str(m) for m in missing), k + 1)
        if not held or not fixed:
            log.error('Capture %d needs at least one marker from EACH object (held: %s, fixed: '
                      '%s). Re-aim so both are clearly in view.', k + 1,
                      sorted(held) or 'none', sorted(fixed) or 'none')
            return False
        T_goal = mloc.estimate_target(self.held_rig, held, corner_views, self.plan)
        if T_goal is None:
            log.error('The held object\'s markers did not agree on its mating frame on capture '
                      '%d -- see the vote above.', k + 1)
            return False
        for mid, T in goal_in_fixed_markers(T_goal, fixed).items():
            self.offsets.setdefault(mid, []).append(T)
        self.goals.append(T_goal)
        self.scans.append(fixed)
        log.info('  capture %d: held mating frame from %d held marker(s), expressed in %d fixed '
                 'marker(s).', k + 1, len(held), len(fixed))
        return True

    def _hand_guide(self, prompt):
        """Software freedrive for ONE prompt, guaranteed off again after."""
        if self.robot.arm.dry_run or prompts_off(self.cfg):
            return True
        rtde_c = getattr(self.robot.arm, 'rtde_c', None)
        try:
            if rtde_c is not None:
                rtde_c.teachMode()
                log.info('SOFTWARE FREEDRIVE ON -- the arm is compliant; push it by hand.')
        except Exception as exc:                  # noqa: BLE001 -- freedrive is a convenience
            log.warning('Could not enter software freedrive (%s) -- use the pendant.', exc)
        try:
            return ask(prompt)
        finally:
            if rtde_c is not None:
                try:
                    rtde_c.endTeachMode()
                except Exception as exc:          # noqa: BLE001
                    log.warning('Could not leave software freedrive (%s).', exc)

    # ---- fuse + check ------------------------------------------------------------------------
    def fuse(self):
        for mid in sorted(self.offsets):
            self.results[mid] = fuse_approaches(self.offsets[mid])
            _T, res_mm, res_deg = self.results[mid]
            n = len(self.offsets[mid])
            log.info('FUSED fixed marker %d over %d capture%s: %.2f mm / %.2f deg spread.',
                     mid, n, '' if n == 1 else 's', res_mm, res_deg)
        return bool(self.results)

    def cross_check(self):
        """Gates (warnings unless capped), fixed-marker agreement, change since last time, and
        the marker-to-marker table for reference."""
        failed = False
        for mid, (_T, res_mm, res_deg) in sorted(self.results.items()):
            for value, key, unit in ((res_mm, 'max_residual_mm', 'mm'),
                                     (res_deg, 'max_residual_deg', 'deg')):
                cap = self.cfg.get(key)
                if cap is not None and value > float(cap):
                    log.error('Fixed marker %d: %.2f %s spread across captures, over %s %.2f.',
                              mid, value, unit, key, float(cap))
                    failed = True
        # The fixed markers must place the goal in the same spot -- one that does not was moved,
        # re-stuck, or printed at a size other than declared.
        if len(self.results) > 1:
            last = self.scans[-1]
            votes = {mid: last[mid][0] @ self.results[mid][0] for mid in last}
            ref = sorted(votes)[0]
            log.info('Fixed-marker agreement on the goal (last capture, vs marker %d):', ref)
            for mid in sorted(votes)[1:]:
                lin, ang = pose_error(votes[ref], votes[mid])
                (log.warning if lin > 0.003 else log.info)(
                    '    %d: %.2f mm / %.2f deg%s', mid, lin * 1000.0, np.degrees(ang),
                    '  <-- check it has not been knocked' if lin > 0.003 else '')
        try:
            prior = tool_frames.load_marker_assemblies(self.cfg).get(self.name)
        except ValueError:
            prior = None
        if prior:
            log.info('Change since the entry already in %s:',
                     tool_frames.marker_assemblies_path(self.cfg))
            for mid in sorted(self.results):
                old = prior['markers'].get(mid)
                if old is None:
                    log.info('    %d: NEW.', mid)
                    continue
                lin, ang = pose_error(old['T_marker_goal'], self.results[mid][0])
                (log.warning if lin > 0.003 else log.info)(
                    '    %d: %+.2f mm / %+.2f deg', mid, lin * 1000.0, np.degrees(ang))
        log.info('Marker to marker at the assembled position (fixed -> held):')
        for fid in sorted(self.results):
            for hid, h in sorted(self.held_rig['markers'].items()):
                xyz, rpy = matrix_to_xyzrpy(marker_to_marker(self.results[fid][0],
                                                             h['T_marker_grasp']))
                log.info('    %d -> %d: xyz %s mm  rpy %s deg', fid, hid,
                         np.round(xyz * 1000.0, 2).tolist(),
                         np.round(np.degrees(rpy), 2).tolist())
        if len(self.goals) < 2:
            log.warning('ONE CAPTURE ONLY -- the residuals are zero by construction. Set '
                        'captures: >= 3, re-seating between them, for a number that means '
                        'something.')
        return not failed

    # ---- write -------------------------------------------------------------------------------
    def write_outputs(self):
        stamp = f'{datetime.now():%Y-%m-%d}'
        markers = {mid: {'size_m': self.fixed_sizes[mid], 'T_marker_goal': T,
                         'meta': {'captures': len(self.offsets[mid]),
                                  'residual_mm': round(res_mm, 2),
                                  'residual_deg': round(res_deg, 2)}}
                   for mid, (T, res_mm, res_deg) in sorted(self.results.items())}
        record = bool(self.cfg.get('record_view_joints', True))
        entry = {'held_object': self.held_name,
                 'dictionary': self.cfg.get_path('aruco.dictionary'),
                 'view_joints': self.q_view if record else None,
                 'markers': markers,
                 'meta': {'captures': len(self.goals), 'measured': stamp}}
        block = entry_block(self.name, entry)
        path = tool_frames.marker_assemblies_path(self.cfg)
        with open(os.path.join(self.out_dir, 'marker_assembly.yaml'), 'w') as fh:
            fh.write(f'# {self.name!r}, calibrated {stamp}. Merged into {path} by the same run.\n'
                     f'marker_assemblies:\n{block}\n')
        self._write_csv()
        if not bool(self.cfg.get('write_catalogue', True)):
            log.info('write_catalogue is off -- %s not touched. The entry:\n\n%s\n', path, block)
            return True
        try:
            catalogue = tool_frames.load_marker_assemblies(path=path)
        except ValueError as exc:
            log.error('%s -- refusing to rewrite the catalogue over a file that does not load.',
                      exc)
            return False
        if os.path.isfile(path):
            shutil.copy2(path, os.path.join(self.out_dir, 'marker_assemblies.yaml.bak'))
        catalogue[self.name] = entry
        with open(path, 'w') as fh:
            fh.write(yaml_document(catalogue, stamp=stamp))
        log.info('WROTE %s (%d assembl%s). This run:\n\n%s\n', path, len(catalogue),
                 'y' if len(catalogue) == 1 else 'ies', block)
        return True

    def _write_csv(self):
        with open(os.path.join(self.out_dir, 'captures.csv'), 'w', newline='') as fh:
            w = _csv.writer(fh)
            w.writerow(_CSV_HEADER)
            for mid in sorted(self.results):
                T_mean = self.results[mid][0]
                rows = iter(self.offsets[mid])
                for k, scan in enumerate(self.scans, start=1):
                    if mid not in scan:
                        continue
                    T = next(rows)
                    xyz, rpy = matrix_to_xyzrpy(T)
                    lin, ang = pose_error(T_mean, T)
                    w.writerow([k, mid, scan[mid][3]]
                               + [round(float(v) * 1000.0, 3) for v in xyz]
                               + [round(float(np.degrees(v)), 3) for v in rpy]
                               + [round(lin * 1000.0, 4), round(float(np.degrees(ang)), 4)])


# ---------------------------------------------------------------------------- entry point
def build_and_run(cfg, robot, camera, args):
    name, held_name = cfg.get('marker_assembly'), cfg.get('held_object')
    if not name:
        log.error('marker_assembly is required -- it is the key this run writes into %s.',
                  tool_frames.marker_assemblies_path(cfg))
        return False
    try:
        objects = tool_frames.load_objects(cfg)
        fixed_sizes = parse_markers(cfg.get('fixed_markers'), 'fixed_markers')
        plan = mloc.ViewPlan(cfg.section('marker_views'))
        q_start = joints_deg(cfg, 'start_joints_deg')
    except ValueError as exc:
        log.error('%s', exc)
        return False
    if held_name not in objects:
        log.error('held_object must name a catalogued object. In %s: %s.',
                  tool_frames.objects_path(cfg), ', '.join(sorted(objects)) or '(none)')
        return False
    held_obj = objects[held_name]
    clash = sorted(set(fixed_sizes) & set(held_obj['markers']))
    if clash:
        log.error('marker id(s) %s are declared on BOTH objects -- a detection could be credited '
                  'to either. Give them distinct ids.', clash)
        return False

    from ..perception import ArucoDetector
    sizes = dict(fixed_sizes)
    sizes.update({mid: m['size_m'] for mid, m in held_obj['markers'].items()})
    detector = ArucoDetector(cfg, sizes_m=sizes)

    out_dir = experiment_dir(cfg, 'marker_assembly_calibration')
    log.info('Output: %s', out_dir)
    log.info('Calibrating %r: %r (markers %s) onto fixed markers %s, %d capture(s). Assemble '
             'them BY HAND first -- nothing is held.', name, held_name,
             sorted(held_obj['markers']),
             ', '.join('%d:%.1fmm' % (m, s * 1000.0) for m, s in sorted(fixed_sizes.items())),
             int(cfg.get('captures', 3)))
    log.info('MARKER SWEEP: %s.', plan.describe())
    cal = _MarkerAssemblyCalibration(cfg, robot, camera, detector, plan, name, held_name,
                                     held_obj, fixed_sizes, out_dir, q_start=q_start)
    robot.arm.set_speed_scale(float(cfg.get_path('speed.phase_scale.visual_localize', 1.0)),
                              'visual_localize')
    root = bt.sequence(
        'marker-assembly-calibration',
        bt.Action('go to the start pose', cal.to_start),
        bt.Action('capture both objects', cal.collect),
        bt.Action('fuse the captures', cal.fuse),
        bt.Action('cross-check', cal.cross_check),
        bt.Action('write marker_assemblies.yaml', cal.write_outputs))
    return bt.run_tree(root, log)


def main():
    # with_gripper=False: nothing is held. The coupler is not touched either.
    run_app('Marker assembly calibration: the held object\'s assembled pose in the fixed '
            'object\'s markers', 'marker_assembly_calibration', build_and_run,
            with_gripper=False, needs_camera=True)


if __name__ == '__main__':
    main()
